---
:api_key: dde08482ed82cb7cb4290aea9f996c9b
:password: aaace3812ccacbc11823ba77192f6a30
:theme_id: 6
:preview_url: https://seguro.lenaatelie.com.br/loja/loja.php?loja=469591&opencode_theme=57cdc795aaca9
